# python3 train.py --mha --decoder "layered" --output_sequence_length 10 --config_path "/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/conf/new/train.yaml"
# python3 train.py --mha --decoder "layered" --output_sequence_length 10 --use_audio --config_path "/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/conf/new/train.yaml"
# python3 train.py --mha --decoder "lstm" --output_sequence_length 3  --config_path "/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/conf/new/train.yaml"
# python3 train.py --mha --decoder "lstm" --output_sequence_length 10 --config_path "/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/conf/new/train.yaml"
# python3 train.py --mha --decoder "lstm" --audio_len 5 --output_sequence_length 10 --config_path "/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/conf/new/train.yaml"
# python3 train.py --mha --decoder "simple" --output_sequence_length 1 --use_audio --config_path "/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/conf/new/train.yaml"
# python3 train.py --mha --decoder "layered" --output_sequence_length 10 --use_audio --audio_encoder "ast" --config_path "/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/conf/new/train.yaml"
# python3 train.py --mha --decoder "simple" --output_sequence_length 3  --config_path "/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/conf/new/train.yaml"
python3 train.py --mha --decoder "layered" --output_sequence_length 3  --config_path "/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/conf/new/train.yaml"
