# image 

fps: 10 #capture image fps
resized_height_v: 75
resized_width_v: 100


sample_rate_audio: 48000
resample_rate_audio: 16000
audio_len: 3 #audio length in seconds


# train augmentation
is_crop: True
crop_percent: 0.1


# dataset
dataset_root: '/home/punygod_admin/SoundSense/soundsense/data/hundred/data'
train_val_split: 0.8

modalities: vg
stack_actions: False
num_stack: 6

# training params
num_workers: 16
batch_size: 32
audio: False


lr: 0.0001
gamma: 0.9
period: 3
epochs: 100
resume: False
log_dir: '/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/'
exp_name: 'mulsa_multimodal_orig_task_2'
gradcam: False
augmentations: False

