# image 
fps: 10 #capture image fps
resized_height_v: 75
resized_width_v: 100

sample_rate_audio: 48000
resample_rate_audio: 16000
audio_len: 3 #audio length in seconds

# train augmentation
# is_crop: False
# crop_percent: 0.1

# dataset
dataset_root: '/home/punygod_admin/SoundSense/soundsense/data/mulsa/data'
train_val_split: 0.9

# model params
encoder_dim: 256
action_dim: 11
num_stack: 6
num_heads: 8
norm_audio: True
use_mha: False
aux_multiplier: 1.0
conv_bottleneck: 128
modalities: vg #vg or vg_ag
stack_past_actions: False
output_model: "aux" # ["seq_pred", "layered", "multi_head", "aux"]
stack_future_actions_dim: 6
input_past_actions: False
input_past_actions_dim: 6
history_encoder_dim: 32


# training params
num_workers: 16
batch_size: 32

lr: 0.0001
gamma: 0.9
period: 3
epochs: 200
resume: False
log_dir: '/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/'
exp_name: 'mulsa_cnn_unimodal_full_task'




