# image 

fps: 10 #capture image fps
resized_height_v: 75
resized_width_v: 100


sample_rate_audio: 48000
resample_rate_audio: 16000
audio_len: 3 #audio length in seconds


# train augmentation
is_crop: True
crop_percent: 0.1

augmentations: False
# dataset
dataset_root: '/home/punygod_admin/SoundSense/soundsense/data/mulsa/data'
train_val_split: 0.8
num_workers: 0
batch_size: 32

# model params
encoder_dim: 256
action_dim: 11
num_stack: 6
num_heads: 8
norm_audio: False
use_mha: True
aux_multiplier: 1.0
conv_bottleneck: 128
modalities: vg #vg or vg_ag
stack_past_actions: False
stack_future_actions: False
stack_future_actions_dim: 6

# training params
lr: 0.0001
gamma: 0.9
period: 3
epochs: 100
resume: False
log_dir: '/home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/'
exp_name: 'mar31-1641'
gradcam: True



