# image 

fps: 10 #capture image fps
resized_height_v: 0
resized_width_v: 0


sample_rate_audio: 48000
resample_rate_audio: 16000
audio_len: 3 #audio length in seconds


# train augmentation
is_crop: True
crop_percent: 0.1

dataset_root: ''
