ablation: vg_ag
action_dim: 3
aux_multiplier: 1.0
batch_size: 32
config: conf/imi/imi_learn.yaml
conv_bottleneck: 128
crop_percent: 0.1
data_folder: ../../data/playbyear_runs
encoder_dim: 256
epochs: 100
exp_name: default
frameskip: 5
gamma: 0.9
lr: 0.0001
nocrop: false
norm_audio: false
num_episode: null
num_heads: 8
num_stack: 6
num_workers: 8
period: 3
resized_height_t: 60
resized_height_v: 75
resized_width_t: 80
resized_width_v: 100
resume: null
task: pouring
train_csv: src/datasets/data/train.csv
use_flow: false
use_mha: false
val_csv: src/datasets/data/val.csv
