action_dim: 8
action_history_length: 0
audio_encoder: spec
audio_len: 5
batch_size: 32
config_path: /home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/conf/new/train.yaml
dataset_root: /home/punygod_admin/SoundSense/soundsense/data/mulsa/dagger_1
decoder: simple
decoder_type: simple
encoder_dim: 256
epochs: 5
exp_name: sorting_imi_vg_ag_simple_seqlen_1_mha_spec_audio_len_5_num_stacks_6
fps: 10
gamma: 0.9
log_dir: /home/punygod_admin/SoundSense/soundsense/models/baselines/mulsa/
loss_weights:
- 0.1
- 0.1
- 0.1
- 0.1
- 0.1
- 0.1
- 0.1
- 0.1
lr: 0.0001
lstm_hidden_layers: 1
mha: true
modalities: vg_ag
norm_audio: true
num_heads: 8
num_stack: 6
num_workers: 16
output_sequence_length: 1
period: 10
resample_rate_audio: 16000
resized_height_v: 75
resized_width_v: 100
resume: false
sample_rate_audio: 16000
train_episodes:
- '28'
- '41'
- '30'
- '64'
- '32'
- '61'
- '6'
- '53'
- '79'
- '40'
- '45'
- '85'
- '50'
- '93'
- '22'
- '15'
- '23'
- '62'
- '52'
- '34'
- '76'
- '92'
- '37'
- '57'
- '58'
- '77'
- '81'
- '20'
- '75'
- '5'
- '29'
- '44'
- '33'
- '47'
- '35'
- '18'
- '1'
- '46'
- '31'
- '54'
- '91'
- '84'
- '49'
- '13'
- '65'
- '59'
- '8'
- '14'
- '60'
- '0'
- '72'
- '70'
- '82'
- '39'
- '24'
- '11'
- '67'
- '99'
- '21'
- '25'
- '63'
- '90'
- '36'
- '96'
- '2'
- '26'
- '12'
- '27'
- '73'
- '43'
- '66'
- '74'
- '38'
- '3'
- '55'
- '68'
- '10'
- '51'
- '95'
- '87'
- '94'
- '42'
- '98'
- '86'
train_val_split: 0.85
use_audio: true
use_mha: true
val_episodes:
- '80'
- '48'
- '16'
- '4'
- '97'
- '71'
- '78'
- '17'
- '83'
- '7'
- '69'
- '19'
- '56'
- '9'
- '88'
